NDFEDIT ;
 ;;4.0; NDF MANAGEMENT;; 1 Jan 99
 W !,"START"
 K ^TMP("NDFEDIT",$J)
 S ^TMP("NDFEDIT",$J,0)=2
 S ^TMP("NDFEDIT",$J,1,0)="ONE"
 S ^TMP("NDFEDIT",$J,2,0)="TWO"
 D EN^VALM("NDF RSB ACCEPT/EDIT")
 W !,"END"
 Q
 ;
EDIT ;
 Q
ACCEPT ;
 Q
BUILD ;
 K ^TMP("NDFEDIT",$J)
 S ^TMP("NDFEDIT",$J,0)=2
 S ^TMP("NDFEDIT",$J,1,0)="ONE"
 S ^TMP("NDFEDIT",$J,2,0)="TWO"
 Q
HDR ;
 S VALMHDR(1)=$$SETSTR^VALM1("HEADER ONE"," ",3,3) Q
