NDFEX ;BIR/DMA-NEW PRODUCTS AND EXCLUDE FROM INTERACTION CHECKING ; 26 Jan 2011  2:36 PM
 ;;4.0; NDF MANAGEMENT;; 1 Jan 99
 ;
GO ;
 N DIR,NDF,NDF1,NDFE,NDFS,X,Y
 K ^TMP($J)
 K DIR S DIR(0)="D",DIR("A")="ENTER START DATE" D ^DIR S NDFS=Y I $D(DUOUT)!$D(DTOUT) G QUIT
 K DIR S DIR(0)="D",DIR("A")="ENTER END DATE" D ^DIR S NDFE=Y+.3 I $D(DUOUT)!$D(DTOUT) G QUIT
 I NDFE<NDFS W !,"END DATE MUST BE GREATER THAN START DATE",! G GO
 S NDF=$Q(^DIA(50.68,"C",NDFS),-1),NDF=$QS(NDF,4)
 F  S NDF=$O(^DIA(50.68,NDF)) Q:'NDF  S NDF1=^(NDF,0) Q:$P(NDF1,"^",2)>NDFE  I $P(NDF1,"^",3)[".01",$P(NDF1,"^",5)="A" S X=$P(^PSNDF(50.68,+NDF1,0),"^")_"^"_$S($G(^(8)):"YES",1:"NO"),^TMP($J,X)=""
 I '$D(^TMP($J)) W !,"NOTHING TO REPORT",! G QUIT
 W !,"PRODUCT",?60,"EXCLUDED",!,"=======",?60,"========",!
 S NDF="" F  S NDF=$O(^TMP($J,NDF)) Q:NDF=""  W !,$P(NDF,"^"),?65,$P(NDF,"^",2)
QUIT K DIR,DTOUT,DUOUT,NDF,NDF1,NDFE,NDFS,X,Y,^TMP($J)
