NDFNWVD ;BIR/WRT-NEW VUID Assignment Report; 12/15/05 10:23
 ;;0.0; NATIONAL DRUG FILE MANAGEMENT SYSTEM;; 30 Oct 98
 K I
 W !,"This report gives you a hard copy of NEW entries with ASSIGNED VUIDs.",!,"In addition, it will reflect entries that have been Inactivated or Re-Activated.",!,"You may queue the report to print, if you wish.",!
 K ^WRT("NDFID") S VUID=$P(^NDFK(5000.991,1,0),"^",2)+1,NUM=1
DVC K %ZIS,POP,IOP S %ZIS="QM",%ZIS("B")="",%ZIS("A")="Select Printer: " D ^%ZIS G:POP DONE W:$E(IOST)'="P" !!,"This report must be run on a printer.",!! G:$E(IOST)'="P" DVC I POP K IOP,POP,IO("Q") Q
QUEUE I $D(IO("Q")) K IO("Q") S ZTRTN="ENQ^NDFNWVD",ZTDESC="List of NEW Entries After VUID Assignment",ZTSAVE("VUID")="",ZTSAVE("NUM")="" D ^%ZTLOAD K ZTSK D ^%ZISC Q
ENQ ;ENTRY POINT WHEN QUEUED
 U IO
 S NDFPGCT=0,NDFPGLNG=IOSL-6 D TITLE,LOOP1,NONE,TITLE1,ACT,NONE,TITLE2,LOOP2,NONE,TITLE2A,ACT2,NONE,TITLE3,LOOP3,NONE,TITLE4,LOOP4,NONE,TITLE4A,ACT4,NONE
DONE W @IOF S:$D(ZTQUEUED) ZTREQ="@" K NDFPRT,IEN,NAM,IFN,DATE,MAST,MASTER,NBR,NUM,STAMP,VUID,DVUID,ENTRY,MJT,NDFPGCT,NDFPGLNG,Y,IOP,POP,IO("Q") K ^BT("PSNVUID") D ^%ZISC
 Q
TITLE I $D(IOF),IOF]"" W @IOF S NDFPGCT=NDFPGCT+1
 S NDFPRT=0 W !,?12," List of NEW Entries After VUID Assignment",!
 W !?27,"VA PRODUCT FILE",!
 S Y=DT X ^DD("DD") W ?22,"Date printed: ",Y,!
 W !,"IEN",?8,"VA PRODUCT NAME",!,?8,"ASSIGNED VUID",?63,"MASTER/NON-MASTER",!
 F MJT=1:1:80 W "-"
 Q
LOOP1 F IEN=0:0 S IEN=$O(^BT("PSNVUID","VAPN",IEN)) Q:'IEN   S NAM=$P(^PSNDF(50.68,IEN,0),"^"),DATE=$P($G(^PSNDF(50.68,IEN,"TERMSTATUS",1,0)),"^"),NODE=^PSNDF(50.68,IEN,"VUID"),VUID=$P(NODE,"^"),MAST=$P(NODE,"^",2) D MASTER,PROP
 Q
MASTER S:MAST=1 MASTER="MASTER" S:MAST=0 MASTER="NON-MASTER"
 Q
 ; See if term exists & set VUID
PROP W !!,IEN,?8,NAM,!,?8,"VUID: ",VUID,?72,MASTER S NDFPRT=1 Q
 Q
ACT S NBR=$P(^NDFK(5000,1,1,50.68,0),"^",2) F  S NBR=$O(^DIA(50.68,NBR)) Q:'NBR  I $P(^(NBR,0),"^",3)=21 S ENTRY=$P(^DIA(50.68,NBR,0),"^") I $D(^PSNDF(50.68,ENTRY,0)) D CHECK
 Q
CHECK I $D(^DIA(50.68,NBR,2.1)),'$D(^DIA(50.68,NBR,3.1)) W !!,ENTRY,?8,$P(^PSNDF(50.68,ENTRY,0),"^"),?67,"RE-ACTIVATED" S NDFPRT=1
 I '$D(^DIA(50.68,NBR,2.1)),$D(^DIA(50.68,NBR,3.1)) S STAMP=$P(^DIA(50.68,NBR,3.1),"^"),Y=STAMP X ^DD("DD") I STAMP>3050310 W !!,ENTRY,?8,$P(^PSNDF(50.68,ENTRY,0),"^"),?67,"INACTIVATED",!?67,Y S NDFPRT=1
 I $D(^DIA(50.68,NBR,2.1)),$D(^DIA(50.68,NBR,3.1)) S STAMP=$P(^DIA(50.68,NBR,3.1),"^"),Y=STAMP X ^DD("DD") I STAMP>3050310 W !!,ENTRY,?8,$P(^PSNDF(50.68,ENTRY,0),"^"),?67,"INACTIVATED",!?67,Y S NDFPRT=1
 Q
TITLE1 I $D(IOF),IOF]"" W @IOF S NDFPGCT=NDFPGCT+1
 S NDFPRT=0 W !,?8," List of Entries Inactivated/Re-Activated in Next Data Update"
 W !,?35,"VA PRODUCT FILE",!
 S Y=DT X ^DD("DD") W ?28,"Date printed: ",Y,!
 W !,?7,"VA PRODUCT NAME",?67,"STATUS",!?67,"DATE",!
 F MJT=1:1:80 W "-"
 Q
 ; Drug Ingredients
TITLE2 I $D(IOF),IOF]"" W @IOF S NDFPRT=0 W !!,?13," List of NEW Entries After VUID Assignment",!
 W !?27,"DRUG INGREDIENTS FILE",!
 S Y=DT X ^DD("DD") W ?25,"Date printed: ",Y,!
 W !,"IEN",?8,"DRUG INGREDIENT",!?8,"ASSIGNED VUID",?63,"MASTER/NON-MASTER",!
 F MJT=1:1:80 W "-"
 Q
LOOP2 K NAM,I
 F IEN=0:0 S IEN=$O(^BT("PSNVUID","ING",IEN)) Q:'IEN   S NAM=$P(^PS(50.416,IEN,0),"^"),DATE=$P($G(^PS(50.416,IEN,"TERMSTATUS",1,0)),"^"),NODE=^PS(50.416,IEN,"VUID"),VUID=$P(NODE,"^"),MAST=$P(NODE,"^",2) D MASTER,PROP
 Q
ACT2 S NBR=$P(^NDFK(5000,1,1,50.416,0),"^",2) F  S NBR=$O(^DIA(50.416,NBR)) Q:'NBR  I $P(^(NBR,0),"^",3)=3 S ENTRY=$P(^DIA(50.416,NBR,0),"^") I $D(^PS(50.416,ENTRY,0)) D CHECK2
 Q
CHECK2 I $D(^DIA(50.416,NBR,2.1)),'$D(^DIA(50.416,NBR,3.1)) W !!,ENTRY,?8,$P(^PS(50.416,ENTRY,0),"^"),?67,"RE-ACTIVATED" S NDFPRT=1
 I '$D(^DIA(50.416,NBR,2.1)),$D(^DIA(50.416,NBR,3.1)) S STAMP=$P(^DIA(50.416,NBR,3.1),"^"),Y=STAMP X ^DD("DD") I STAMP>3050310 W !!,ENTRY,?8,$P(^PS(50.416,ENTRY,0),"^"),?67,"INACTIVATED",!?67,Y S NDFPRT=1
 I $D(^DIA(50.416,NBR,2.1)),$D(^DIA(50.416,NBR,3.1)) S STAMP=$P(^DIA(50.416,NBR,3.1),"^"),Y=STAMP X ^DD("DD") I STAMP>3050310 W !!,ENTRY,?8,$P(^PS(50.416,ENTRY,0),"^"),?67,"INACTIVATED",!?67,Y S NDFPRT=1
 Q
TITLE2A I $D(IOF),IOF]"" W @IOF S NDFPRT=0 W !!,?11," List of Entries Inactivated/Re-Activated in Next Data Update"
 W !,?35,"DRUG INGREDIENTS FILE",!
 S Y=DT X ^DD("DD") W ?33,"Date printed: ",Y,!
 W !,?7,"DRUG INGREDIENT",?67,"STATUS",!?67,"DATE",!
 F MJT=1:1:80 W "-"
 Q
NONE W:NDFPRT=0 !," 0 ENTRIES FOUND"
 Q
 ; VA Drug Class
TITLE3 I $D(IOF),IOF]"" W @IOF S NDFPRT=0 W !!,?13," List of NEW Entries After VUID Assignment",!
 W !?27,"VA DRUG CLASS",!
 S Y=DT X ^DD("DD") W ?22,"Date printed: ",Y,!
 W !,"IEN",?8,"VA DRUG CLASS",!?8,"ASSIGNED VUID",?63,"MASTER/NON-MASTER",!
 F MJT=1:1:80 W "-"
 Q
LOOP3 K NAM,I
 F IEN=0:0 S IEN=$O(^BT("PSNVUID","VACL",IEN)) Q:'IEN  D SET
 Q
SET S NAM=$P(^PS(50.605,IEN,0),"^"),DATE=$P($G(^PS(50.605,IEN,"TERMSTATUS",1,0)),"^"),NODE=^PS(50.605,IEN,"VUID"),VUID=$P(NODE,"^"),MAST=$P(NODE,"^",2) D MASTER,PROP
 Q
 ; VA Generic
TITLE4 I $D(IOF),IOF]"" W @IOF S NDFPRT=0 W !!,?13," List of NEW Entries After VUID Assignment",!
 W !?27,"VA GENERIC FILE",!
 S Y=DT X ^DD("DD") W ?22,"Date printed: ",Y,!
 W !,"IEN",?8,"VA GENERIC NAME",!?8,"ASSIGNED VUID",?63,"MASTER/NON-MASTER",!
 F MJT=1:1:80 W "-"
 Q
LOOP4 K NAM,I
 F IEN=0:0 S IEN=$O(^BT("PSNVUID","VAGN",IEN)) Q:'IEN   S NAM=$P(^PSNDF(50.6,IEN,0),"^"),DATE=$P($G(^PSNDF(50.6,IEN,"TERMSTATUS",1,0)),"^"),NODE=^PSNDF(50.6,IEN,"VUID"),VUID=$P(NODE,"^"),MAST=$P(NODE,"^",2) D MASTER,PROP
 Q
ACT4 S NBR=$P(^NDFK(5000,1,1,50.6,0),"^",2) F  S NBR=$O(^DIA(50.6,NBR)) Q:'NBR  I $P(^(NBR,0),"^",3)=1 S ENTRY=$P(^DIA(50.6,NBR,0),"^") I $D(^PSNDF(50.6,ENTRY,0)) D CHECK4
 Q
CHECK4 I $D(^DIA(50.6,NBR,2.1)),'$D(^DIA(50.6,NBR,3.1)) W !!,ENTRY,?8,$P(^PSNDF(50.6,ENTRY,0),"^"),?67,"RE-ACTIVATED" S NDFPRT=1
 I '$D(^DIA(50.6,NBR,2.1)),$D(^DIA(50.6,NBR,3.1)) S STAMP=$P(^DIA(50.6,NBR,3.1),"^"),Y=STAMP X ^DD("DD") I STAMP>3050310 W !!,ENTRY,?8,$P(^PSNDF(50.6,ENTRY,0),"^"),?67,"INACTIVATED",!?67,Y S NDFPRT=1
 I $D(^DIA(50.6,NBR,2.1)),$D(^DIA(50.6,NBR,3.1)) S STAMP=$P(^DIA(50.6,NBR,3.1),"^"),Y=STAMP X ^DD("DD") I STAMP>3050310 W !!,ENTRY,?8,$P(^PSNDF(50.6,ENTRY,0),"^"),?67,"INACTIVATED",!?67,Y S NDFPRT=1
 Q
TITLE4A I $D(IOF),IOF]"" W @IOF S NDFPRT=0 W !!,?11," List of Entries Inactivated/Re-Activated in Next Data Update"
 W !,?35,"VA GENERIC FILE",!
 S Y=DT X ^DD("DD") W ?30,"Date printed: ",Y,!
 W !,?7,"VA GENERIC NAME",?67,"STATUS",!?67,"DATE",!
 F MJT=1:1:80 W "-"
 Q
